version: "3.9"
services:
  # app:
  #   platform: "linux/amd64"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       NEXT_PUBLIC_CLIENTVAR: "clientvar"
  #   working_dir: /app
  #   ports:
  #     - "3000:3000"
  #   image: t3-app
  #   environment:
  #     - DATABASE_URL=database_url_goes_here
    db:
      image: postgres:latest
      restart: always
      ports:
        - 9000:5432
      environment:
        - POSTGRES_USER=develop
        - POSTGRES_DB=develop
        - POSTGRES_PASSWORD=develop