import { type NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/Layout";
import { UploadFile } from "../components/UploadFile";

import { GuideListItem } from "../components/GuideList";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const { data } = api.guides.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Medical Chest - Admin panel</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="grid h-full grid-cols-2 grid-rows-1 gap-2">
          <div className="h-full bg-brand text-white">
            <UploadFile />
          </div>

          <div className="h-full overflow-hidden">
            <ul className="h-full overflow-y-auto overflow-x-hidden">
              {data?.map((guide) => (
                <GuideListItem
                  key={guide.id}
                  guideId={guide.id}
                  guideName={guide.name}
                  guideNumber={guide.guideNumber}
                  guideLang={guide.lang as "da-DK" | "en-GB"}
                />
              ))}
            </ul>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Home;
